baseURL = 'https://ankilangs.org/'
languageCode = 'en-us'
title = 'AnkiLangs'

enableGitInfo = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
  BookLogo = 'logo.png'
  BookLastChangeLink = 'https://github.com/ankilangs/ankilangs/commit/{{ .GitInfo.Hash }}'
  BookEditLink = 'https://github.com/ankilangs/ankilangs/edit/main/website/{{ .Path }}'
